---
title: "SOK1016, vår 2023, Mappeoppgave 1"
author: "12"
format: pdf
echo: true
output: true
editor: visual
warning: false
editor_options: 
  chunk_output_type: console
---

```{r, message=FALSE, warning=FALSE}
# output | false
rm(list=ls()) 
library(tidyverse)
library(rjstat)
library(httr)
library(zoo)
```

```{r}
url <- "https://data.ssb.no/api/v0/no/table/09171/"

query <- '{
  "query": [
    {
      "code": "NACE",
      "selection": {
        "filter": "item",
        "values": [
          "nr23_6",
          "pub2X01_02",
          "pub2X03",
          "pub2X05",
          "nr2X06_09",
          "nr23ind",
          "pub2X35",
          "pub2X36_39",
          "pub2X41_43",
          "pub2X45_47",
          "pub2X49B",
          "pub2X50A",
          "pub2X49A_52",
          "pub2X53",
          "pub2X55_56",
          "pub2X58_63",
          "pub2X64_66",
          "pub2X68A",
          "pub2X68B",
          "pub2X69_75",
          "pub2X77_82",
          "pub2X84",
          "pub2X85",
          "pub2X86_88",
          "pub2X90_97"
        ]
      }
    },
    {
      "code": "ContentsCode",
      "selection": {
        "filter": "item",
        "values": [
          "Prob",
          "Pin",
          "BNPB",
          "Prob2",
          "PIN2",
          "BNPB2",
          "BNPB2ses"
        ]
      }
    },
    {
      "code": "Tid",
      "selection": {
        "filter": "item",
        "values": [
          "2011K1",
          "2011K2",
          "2011K3",
          "2011K4",
          "2012K1",
          "2012K2",
          "2012K3",
          "2012K4",
          "2013K1",
          "2013K2",
          "2013K3",
          "2013K4",
          "2014K1",
          "2014K2",
          "2014K3",
          "2014K4",
          "2015K1",
          "2015K2",
          "2015K3",
          "2015K4",
          "2016K1",
          "2016K2",
          "2016K3",
          "2016K4",
          "2017K1",
          "2017K2",
          "2017K3",
          "2017K4",
          "2018K1",
          "2018K2",
          "2018K3",
          "2018K4",
          "2019K1",
          "2019K2",
          "2019K3",
          "2019K4",
          "2020K1",
          "2020K2",
          "2020K3",
          "2020K4",
          "2021K1",
          "2021K2",
          "2021K3",
          "2021K4"
        ]
      }
    }
  ],
  "response": {
    "format": "json-stat2"
  }
}'

hent_indeks.tmp <- url %>%
  POST(body = query, encode = "json")

df_1 <-  hent_indeks.tmp %>%
  content("text") %>%
  fromJSONstat() %>%
  as_tibble()
```

```{r}
url <- "https://data.ssb.no/api/v0/no/table/09174/"

query <- '{
  "query": [
    {
      "code": "NACE",
      "selection": {
        "filter": "vs:NRNaeringPubAgg",
        "values": [
          "pub2X01_02",
          "pub2X03",
          "pub2X05",
          "nr2X06_09",
          "nr23ind",
          "pub2X35",
          "pub2X36_39",
          "pub2X41_43",
          "pub2X45_47",
          "pub2X49B",
          "pub2X50A",
          "pub2X49A_52",
          "pub2X53",
          "pub2X55_56",
          "pub2X58_63",
          "pub2X64_66",
          "pub2X68A",
          "pub2X68B",
          "pub2X69_75",
          "pub2X77_82",
          "pub2X84",
          "pub2X85",
          "pub2X86_88",
          "pub2X90_97"
        ]
      }
    },
    {
      "code": "ContentsCode",
      "selection": {
        "filter": "item",
        "values": [
          "SysselsattNorm"
        ]
      }
    },
    {
      "code": "Tid",
      "selection": {
        "filter": "item",
        "values": [
          "2021"
        ]
      }
    }
  ],
  "response": {
    "format": "json-stat2"
  }
}'

hent_indeks.tmp <- url %>%
  POST(body = query, encode = "json")

df_årsverk <-  hent_indeks.tmp %>%
  content("text") %>%
  fromJSONstat() %>%
  as_tibble()

```

```{r}
df_nasjonalregnskap <- df_1 %>%
  filter(kvartal == "2021K1" | 
           kvartal == "2021K2" | 
           kvartal == "2021K3" | 
           kvartal == "2021K4") %>% 
  rename(var=statistikkvariabel) %>%
  group_by(næring, var) %>% 
  mutate(årlig_næring=sum(value)) %>% 
  filter(kvartal == "2021K1")
  
df_nasjonalregnskap[is.na(df_nasjonalregnskap)] <- 0
```

```{r}
df_nasjonalregnskap <- df_nasjonalregnskap %>%
  select(-(value)) %>% 
  pivot_wider(names_from=var, values_from = årlig_næring) %>% 
  mutate(År=as.integer(2021)) %>% 
  select(-c(kvartal)) %>% 
  relocate(År, .before = næring) %>% 
  pivot_longer(3:9, names_to = "var", values_to = "values") %>% 
  pivot_wider(names_from=næring, values_from=values) %>%
  mutate(`Industri og Bergverksdrift` = Industri + Bergverksdrift) %>%
  mutate(Primærnæringene = `Jordbruk og skogbruk` 
         + `Fiske, fangst og akvakultur`) %>%
  mutate(`Tjenester og ellers` = `Vannforsyning, avløp og renovasjon` + `Elektrisitets-, gass- og varmtvannsforsyning`) %>% 
  mutate(`Finansiell og forretningsmessig tjenesteyting, eiendomsdrift` = `Finansierings- og forsikringsvirksomhet` + `Forretningsmessig tjenesteyting` + `Omsetning og drift av fast eiendom` + `Boligtjenester, egen bolig`) %>% 
  mutate(Samferdsel = Rørtransport + `Informasjon og kommunikasjon` + `Utenriks sjøfart` + `Transport utenom utenriks sjøfart` + `Post og distribusjonsvirksomhet`) %>% 
  mutate(`Varehandel, hotell og resturantvirksomhet` = `Varehandel og reparasjon av motorvogner` + `Overnattings- og serveringsvirksomhet`) %>%
  mutate(`Helse- og sosialtjenester` = `Helse- og omsorgstjenester`, `Kultur, underholdning og annen tjenesteyting`, `Faglig, vitenskapelig og teknisk tjenesteyting`) %>% 
  select(-c(Industri, Bergverksdrift, `Jordbruk og skogbruk`, `Fiske, fangst og akvakultur`, `Finansierings- og forsikringsvirksomhet`, `Finansierings- og forsikringsvirksomhet`, `Forretningsmessig tjenesteyting`, `Omsetning og drift av fast eiendom`, Rørtransport, `Informasjon og kommunikasjon`, `Utenriks sjøfart`, `Transport utenom utenriks sjøfart`, `Post og distribusjonsvirksomhet`, `Totalt for næringer`, `Varehandel og reparasjon av motorvogner`, `Overnattings- og serveringsvirksomhet`, `Boligtjenester, egen bolig`, `Helse- og omsorgstjenester`, `Kultur, underholdning og annen tjenesteyting`, `Faglig, vitenskapelig og teknisk tjenesteyting`, `Vannforsyning, avløp og renovasjon`, `Elektrisitets-, gass- og varmtvannsforsyning`))
  
```

```{r}
df_nasjonalregnskap <- df_nasjonalregnskap %>%
  pivot_longer(3:13, names_to = "næring", values_to = "values") %>% 
  pivot_wider(names_from=var, values_from = values)
```

```{r}
df_oppg1 <- df_nasjonalregnskap %>% 
  select(c(År,næring,`Bruttoprodukt i basisverdi. Løpende priser (mill. kr)`,`Produksjon i basisverdi. Løpende priser (mill. kr)`))
```

```{r}
df_årsverk <- df_årsverk %>% 
  pivot_wider(names_from = statistikkvariabel, values_from = value) %>% 
  pivot_wider(names_from = næring, values_from = `Årsverk, heltidsekvivalenter, for lønnstakere og selvstendige (1 000 årsverk)`) %>%
  mutate(`Industri og Bergverksdrift` = Industri + Bergverksdrift) %>%
  mutate(Primærnæringene = `Jordbruk og skogbruk` 
         + `Fiske, fangst og akvakultur`) %>%
  mutate(`Tjenester og ellers` = `Vannforsyning, avløp og renovasjon` + `Elektrisitets-, gass- og varmtvannsforsyning`) %>% 
  mutate(`Finansiell og forretningsmessig tjenesteyting, eiendomsdrift` = `Finansierings- og forsikringsvirksomhet` + `Forretningsmessig tjenesteyting` + `Omsetning og drift av fast eiendom`+ `Boligtjenester, egen bolig` ) %>% 
  mutate(Samferdsel = Rørtransport + `Informasjon og kommunikasjon` + `Utenriks sjøfart` + `Transport utenom utenriks sjøfart` + `Post og distribusjonsvirksomhet`) %>% 
  mutate(`Varehandel, hotell og resturantvirksomhet` = `Varehandel og reparasjon av motorvogner` + `Overnattings- og serveringsvirksomhet`) %>%
  mutate(`Helse- og sosialtjenester` = `Helse- og omsorgstjenester`, `Kultur, underholdning og annen tjenesteyting`, `Faglig, vitenskapelig og teknisk tjenesteyting`) %>% 
  select(-c(Industri, Bergverksdrift, `Jordbruk og skogbruk`, `Fiske, fangst og akvakultur`, `Finansierings- og forsikringsvirksomhet`, `Finansierings- og forsikringsvirksomhet`, `Forretningsmessig tjenesteyting`, `Omsetning og drift av fast eiendom`, Rørtransport, `Informasjon og kommunikasjon`, `Utenriks sjøfart`, `Transport utenom utenriks sjøfart`, `Post og distribusjonsvirksomhet`, `Varehandel og reparasjon av motorvogner`, `Overnattings- og serveringsvirksomhet`, `Boligtjenester, egen bolig`, `Helse- og omsorgstjenester`, `Kultur, underholdning og annen tjenesteyting`, `Faglig, vitenskapelig og teknisk tjenesteyting`, `Vannforsyning, avløp og renovasjon`, `Elektrisitets-, gass- og varmtvannsforsyning`))%>%
  pivot_longer(2:12, names_to = "næring", values_to = "Årsverk, heltidsekvivalenter, for lønnstakere og selvstendige (1 000 årsverk)")
  
```

```{r}
df_oppg1 <- cbind(df_oppg1,df_årsverk$`Årsverk, heltidsekvivalenter, for lønnstakere og selvstendige (1 000 årsverk)`)
df_oppg1 <- df_oppg1 %>% 
  rename(sysselsatte_årsverk="df_årsverk$`Årsverk, heltidsekvivalenter, for lønnstakere og selvstendige (1 000 årsverk)`") %>%
  mutate(Total_næring_bruttopr=sum(`Bruttoprodukt i basisverdi. Løpende priser (mill. kr)`)) %>% 
  mutate(Total_næring_prod=sum(`Produksjon i basisverdi. Løpende priser (mill. kr)`)) %>% 
  mutate(Total_næring_ss=sum(`sysselsatte_årsverk`)) %>%     
  mutate(andel_bruttoprodukt_prosent = 100*(`Bruttoprodukt i basisverdi. Løpende priser (mill. kr)`/Total_næring_bruttopr)) %>%
  mutate(andel_produksjon_prosent = 100*(`Produksjon i basisverdi. Løpende priser (mill. kr)`/Total_næring_prod)) %>% 
  mutate(andel_sysselsatte_prosent = 100*(`sysselsatte_årsverk`/Total_næring_ss))
  
```

```{r}
df_andel <- df_oppg1 %>% 
  select(c(næring,andel_bruttoprodukt_prosent,andel_produksjon_prosent, andel_sysselsatte_prosent))
df_andel <- df_andel %>% 
  pivot_longer(2:4, names_to = "andel", values_to = "prosent")
```

```{r}
df_andel %>% 
  ggplot(aes(x=næring, y=prosent, fill=andel))+
  geom_bar(position = "dodge", stat="identity")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

```{r}
df_sammenligning <- df_oppg1 %>% 
  select(c(næring, `Bruttoprodukt i basisverdi. Løpende priser (mill. kr)`, `Produksjon i basisverdi. Løpende priser (mill. kr)`, sysselsatte_årsverk))
df_sammenligning1 <- df_sammenligning
df_sammenligning <- df_sammenligning %>%
  select(-(sysselsatte_årsverk)) %>% 
  pivot_longer(2:3, names_to = "sammenligning", values_to = "value")
df_sammenligning1 <- df_sammenligning1 %>% 
  mutate(bruttop_per_ss= `Bruttoprodukt i basisverdi. Løpende priser (mill. kr)` / sysselsatte_årsverk)
```

```{r}
df_sammenligning1 %>% 
  ggplot(aes(x=næring, y=bruttop_per_ss))+
  geom_bar(position = "dodge", stat="identity")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

```{r}
df_sammenligning %>% 
  ggplot(aes(x=næring, y=value, fill=sammenligning))+
  geom_bar(position = "dodge", stat="identity")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

## Oppgave 3

```{r}
df_1 <- df_1 %>% 
  rename(var=statistikkvariabel) %>% 
  pivot_wider(names_from = var, values_from = value)
df_2 <- df_1 %>% 
  select(c(næring,kvartal,`Bruttoprodukt i basisverdi. Løpende priser (mill. kr)`, `Bruttoprodukt i basisverdi. Faste 2020-priser (mill. kr)`))
```

```{r}
df_total <- df_2
df_2 <- df_2 %>% 
  pivot_longer(3:4, names_to= "bruttoprodukt", values_to= "value") %>% 
  pivot_wider(names_from=næring, values_from=value) %>% 
  mutate(`Industri og Bergverksdrift` = Industri + Bergverksdrift) %>%
  mutate(Primærnæringene = `Jordbruk og skogbruk` 
         + `Fiske, fangst og akvakultur`) %>%
  mutate(`Tjenester og ellers` = `Vannforsyning, avløp og renovasjon` + `Elektrisitets-, gass- og varmtvannsforsyning`) %>% 
  mutate(`Finansiell og forretningsmessig tjenesteyting, eiendomsdrift` = `Finansierings- og forsikringsvirksomhet` + `Forretningsmessig tjenesteyting` + `Omsetning og drift av fast eiendom` ) %>% 
  mutate(Samferdsel = Rørtransport + `Informasjon og kommunikasjon` + `Utenriks sjøfart` + `Transport utenom utenriks sjøfart` + `Post og distribusjonsvirksomhet`) %>% 
  mutate(`Varehandel, hotell og resturantvirksomhet` = `Varehandel og reparasjon av motorvogner` + `Overnattings- og serveringsvirksomhet`) %>%
  mutate(`Helse- og sosialtjenester` = `Helse- og omsorgstjenester`, `Kultur, underholdning og annen tjenesteyting`, `Faglig, vitenskapelig og teknisk tjenesteyting`) %>% 
  select(-c(Industri, Bergverksdrift, `Jordbruk og skogbruk`, `Fiske, fangst og akvakultur`, `Finansierings- og forsikringsvirksomhet`, `Finansierings- og forsikringsvirksomhet`, `Forretningsmessig tjenesteyting`, `Omsetning og drift av fast eiendom`, Rørtransport, `Informasjon og kommunikasjon`, `Utenriks sjøfart`, `Transport utenom utenriks sjøfart`, `Post og distribusjonsvirksomhet`, `Totalt for næringer`, `Varehandel og reparasjon av motorvogner`, `Overnattings- og serveringsvirksomhet`, `Boligtjenester, egen bolig`, `Helse- og omsorgstjenester`, `Kultur, underholdning og annen tjenesteyting`, `Faglig, vitenskapelig og teknisk tjenesteyting`, `Vannforsyning, avløp og renovasjon`, `Elektrisitets-, gass- og varmtvannsforsyning`)) %>% 
  pivot_longer(3:13, names_to = "næring", values_to = "value")
```

```{r}
df_3 <- df_2
df_3 <- df_3 %>% 
  filter(bruttoprodukt == "Bruttoprodukt i basisverdi. Løpende priser (mill. kr)") 

df_3$kvartal <- gsub("K1", "", as.character(df_3$kvartal))
df_3$kvartal <- gsub("K2", "", as.character(df_3$kvartal)) 
df_3$kvartal <- gsub("K3", "", as.character(df_3$kvartal))
df_3$kvartal <- gsub("K4", "", as.character(df_3$kvartal)) 
df_3 <- df_3%>%
  mutate(kvartal=as.numeric(kvartal)) %>% 
  group_by(næring, kvartal) %>% 
  mutate(årlig_næring=sum(value))
```

```{r}
df_3 %>% 
  ggplot(aes(x=kvartal, y=årlig_næring, col=næring))+
  geom_line()
```

```{r}
df_4 <- df_2
df_4 <- df_4 %>% 
  filter(bruttoprodukt == "Bruttoprodukt i basisverdi. Faste 2020-priser (mill. kr)") 

df_4$kvartal <- gsub("K1", "", as.character(df_4$kvartal))
df_4$kvartal <- gsub("K2", "", as.character(df_4$kvartal)) 
df_4$kvartal <- gsub("K3", "", as.character(df_4$kvartal))
df_4$kvartal <- gsub("K4", "", as.character(df_4$kvartal)) 
df_4 <- df_4%>%
  mutate(kvartal=as.numeric(kvartal)) %>% 
  group_by(næring, kvartal) %>% 
  mutate(årlig_næring=sum(value))
```

```{r}
df_4 %>% 
  ggplot(aes(x=kvartal, y=årlig_næring, col=næring))+
  geom_line()
```

```{r}
df_total <- df_total %>% 
  filter(næring == "Totalt for næringer")
df_total$kvartal <- gsub("K1", "", as.character(df_total$kvartal))
df_total$kvartal <- gsub("K2", "", as.character(df_total$kvartal)) 
df_total$kvartal <- gsub("K3", "", as.character(df_total$kvartal))
df_total$kvartal <- gsub("K4", "", as.character(df_total$kvartal)) 
df_total <- df_total%>%
  mutate(kvartal=as.numeric(kvartal)) %>% 
  group_by(næring, kvartal) %>% 
  mutate(årlig_løpende=sum(`Bruttoprodukt i basisverdi. Løpende priser (mill. kr)`)) %>% 
  mutate(årlig_faste=sum(`Bruttoprodukt i basisverdi. Faste 2020-priser (mill. kr)`)) %>% 
  pivot_longer(5:6, names_to = "Bruttoprodukt", values_to = "value")
  
```

```{r}
df_total %>% 
  ggplot(aes(x=kvartal, y= value, col=Bruttoprodukt))+
  geom_line()
```
